#!/usr/bin/env python

from subprocess import call,PIPE, Popen
from os.path import expanduser
from sys import version_info
from argparse import ArgumentParser
import toml

def test_port(ip,port,udp=False):
    port = str(port)
    if udp:
        cmd = ("/usr/bin/nc","-z","-w2","-u",ip,port)
    else:
        cmd = ("/usr/bin/nc","-z","-w2",ip,port)
    ret = call(cmd)
    if ret:
        if udp:
            print("%s:%s/udp is not open"%(ip,port))
        else:
            print("%s:%s/tcp is not open"%(ip,port))
        return 1
    else:
        return 0

def test_machine(ip,tcp_ports=None,udp_ports=None,extra_tests=None):
    errors = 0
    ret = call(("ping","-c1","-W1",ip),stdout=PIPE)
    if ret:
        print("Couldn't ping '%s'"%ip)
        errors += 1
    else:
        if tcp_ports:
            for port in tcp_ports:
                errors += test_port(ip,port)
        if udp_ports:
            for port in udp_ports:
                errors += test_port(ip,port,udp=True)
        if extra_tests:
            for t in extra_tests:
                if t():
                    errors += 1
    return errors

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("cfg_file",default="sst.cfg",nargs='?')
    args = parser.parse_args()

    errors = 0
    config = toml.load(args.cfg_file)
    for addr,opts in config.items():
        if "extra_tests" in opts:
            opts["extra_tests"] = [ lambda: call(expanduser(x["script"])) for x in opts["extra_tests"].values() ]
        errors += test_machine(addr,**opts)
    exit(errors)
